
#ifndef CONTROLLER_DATATYPES_H_
#define CONTROLLER_DATATYPES_H_
// Fault codes
typedef enum {
	CAN_CONTROLLER_FAULT_IDENTIFICATION = 0,
  CAN_CONTROLLER_FAULT_OVER_VOLTAGE,
  CAN_CONTROLLER_FAULT_UNDER_VOLTAGE,
  CAN_CONTROLLER_FAULT_STALL = 4,
  CAN_CONTROLLER_FAULT_INTERNAL_VOLTS, 
  CAN_CONTROLLER_FAULT_CONTROLLER_OVER_TEMPERATURE,
  CAN_CONTROLLER_FAULT_THROTTLE_POWER_UP,
  CAN_CONTROLLER_FAULT_INTERNAL_RESET = 9,
  CAN_CONTROLLER_FAULT_HALL_THROTTLE_OPEN_OR_SHORTED,
  CAN_CONTROLLER_FAULT_ANGLE_SENSOR,
  CAN_CONTROLLER_FAULT_MOTOR_OVER_TEMPERATURE = 14,
} CAN_CONTROLLER_FAULT;

#endif /* DATATYPES_H_ */
